language: python

python:
    - "2.7"

install:
    - pip install flake8
    - pip install -r requirements.txt

notifications:
    email:
        - opensource@spatialcurrent.io

before_script:
    flake8 sgol

script: python -m unittest sgol.test
